"""initial schema

Revision ID: a8366bafdaf5
Revises:
Create Date: 2026-04-19 16:36:44.634903

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8366bafdaf5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scanners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_scanner_name_version"),
    )
    with op.batch_alter_table("scanners", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scanners_name"), ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("date_modified", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fps_num", sa.Integer(), nullable=True),
        sa.Column("fps_den", sa.Integer(), nullable=True),
        sa.Column("total_frames", sa.Integer(), nullable=True),
        sa.Column("container", sa.String(length=32), nullable=True),
        sa.Column("codec", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scan_progress_percent", sa.Float(), nullable=False),
        sa.Column("scan_started_at", sa.DateTime(), nullable=True),
        sa.Column("preview_proxy_status", sa.String(length=16), nullable=False),
        sa.Column("preview_proxy_started_at", sa.DateTime(), nullable=True),
        sa.Column("preview_proxy_progress_percent", sa.Float(), nullable=False),
        sa.Column("preview_proxy_error_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_videos_path"), ["path"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_videos_preview_proxy_status"),
            ["preview_proxy_status"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_videos_status"), ["status"], unique=False)

    op.create_table(
        "compositions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("scanner_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["scanner_id"], ["scanners.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subtitle_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("origin", sa.String(length=1024), nullable=False),
        sa.Column("cue_count", sa.Integer(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.Column("meta_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "video_id", "source", "origin", name="uq_subtitle_track_video_source_origin"
        ),
    )
    with op.batch_alter_table("subtitle_tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subtitle_tracks_language"), ["language"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_tracks_video_id"), ["video_id"], unique=False
        )

    op.create_table(
        "export_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("composition_id", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("scale_divisor", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("output_path", sa.String(length=1024), nullable=True),
        sa.Column("progress_percent", sa.Float(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["composition_id"], ["compositions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("scanner_name", sa.String(length=64), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("start_pts_seconds", sa.Float(), nullable=False),
        sa.Column("end_pts_seconds", sa.Float(), nullable=False),
        sa.Column("thumbnail_path", sa.String(length=1024), nullable=True),
        sa.Column("meta_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("end_frame > start_frame", name="ck_segment_frames_valid"),
        sa.ForeignKeyConstraint(["scan_run_id"], ["scan_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_segment_video_scanner_start",
            ["video_id", "scanner_name", "start_frame"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_segments_scanner_name"), ["scanner_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_segments_video_id"), ["video_id"], unique=False
        )

    op.create_table(
        "subtitle_cues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("start_pts_seconds", sa.Float(), nullable=False),
        sa.Column("end_pts_seconds", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"], ["subtitle_tracks.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "track_id", "ordinal", name="uq_subtitle_cue_track_ordinal"
        ),
    )
    with op.batch_alter_table("subtitle_cues", schema=None) as batch_op:
        batch_op.create_index(
            "ix_subtitle_cue_video_frames", ["video_id", "start_frame"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_cues_language"), ["language"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_cues_track_id"), ["track_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_cues_video_id"), ["video_id"], unique=False
        )

    # SQLite-only: FTS5 contentless index over subtitle_cues.text, kept in
    # sync via three triggers. SQLAlchemy metadata can't model virtual
    # tables or triggers natively, so they're declared here.
    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            "CREATE VIRTUAL TABLE IF NOT EXISTS subtitle_cues_fts USING fts5("
            "text, content='subtitle_cues', content_rowid='id', "
            "tokenize='porter unicode61')"
        )
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS subtitle_cues_ai "
            "AFTER INSERT ON subtitle_cues BEGIN "
            "INSERT INTO subtitle_cues_fts(rowid, text) VALUES (new.id, new.text); "
            "END"
        )
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS subtitle_cues_ad "
            "AFTER DELETE ON subtitle_cues BEGIN "
            "INSERT INTO subtitle_cues_fts(subtitle_cues_fts, rowid, text) "
            "VALUES ('delete', old.id, old.text); END"
        )
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS subtitle_cues_au "
            "AFTER UPDATE ON subtitle_cues BEGIN "
            "INSERT INTO subtitle_cues_fts(subtitle_cues_fts, rowid, text) "
            "VALUES ('delete', old.id, old.text); "
            "INSERT INTO subtitle_cues_fts(rowid, text) VALUES (new.id, new.text); "
            "END"
        )

    op.create_table(
        "composition_clips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("composition_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("trim_start_frame", sa.Integer(), nullable=False),
        sa.Column("trim_end_frame", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "trim_start_frame >= 0 AND trim_end_frame >= 0", name="ck_trim_nonneg"
        ),
        sa.ForeignKeyConstraint(
            ["composition_id"], ["compositions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["segment_id"], ["segments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "composition_id", "position", name="uq_composition_clip_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("composition_clips")
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS subtitle_cues_au")
        op.execute("DROP TRIGGER IF EXISTS subtitle_cues_ad")
        op.execute("DROP TRIGGER IF EXISTS subtitle_cues_ai")
        op.execute("DROP TABLE IF EXISTS subtitle_cues_fts")
    with op.batch_alter_table("subtitle_cues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtitle_cues_video_id"))
        batch_op.drop_index(batch_op.f("ix_subtitle_cues_track_id"))
        batch_op.drop_index(batch_op.f("ix_subtitle_cues_language"))
        batch_op.drop_index("ix_subtitle_cue_video_frames")

    op.drop_table("subtitle_cues")
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segments_video_id"))
        batch_op.drop_index(batch_op.f("ix_segments_scanner_name"))
        batch_op.drop_index("ix_segment_video_scanner_start")

    op.drop_table("segments")
    op.drop_table("export_jobs")
    with op.batch_alter_table("subtitle_tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtitle_tracks_video_id"))
        batch_op.drop_index(batch_op.f("ix_subtitle_tracks_language"))

    op.drop_table("subtitle_tracks")
    op.drop_table("scan_runs")
    op.drop_table("compositions")
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_videos_status"))
        batch_op.drop_index(batch_op.f("ix_videos_preview_proxy_status"))
        batch_op.drop_index(batch_op.f("ix_videos_path"))

    op.drop_table("videos")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("scanners", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scanners_name"))

    op.drop_table("scanners")
    # ### end Alembic commands ###
